"""initial p0 schema

Revision ID: bbfa08bf4a36
Revises: 
Create Date: 2026-09-24 10:54:37.226434
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bbfa08bf4a36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_no', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.SmallInteger(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Enum('active', 'maintenance', 'retired', name='bus_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buses')),
    sa.UniqueConstraint('registration_no', name=op.f('uq_buses_registration_no'))
    )
    op.create_table('domain_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_type', sa.String(length=32), nullable=True),
    sa.Column('aggregate_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_events'))
    )
    op.create_index('ix_domain_events_aggregate', 'domain_events', ['aggregate_type', 'aggregate_id'], unique=False)
    op.create_index(op.f('ix_domain_events_occurred_at'), 'domain_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_domain_events_type'), 'domain_events', ['type'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes')),
    sa.UniqueConstraint('code', name=op.f('uq_routes_code'))
    )
    op.create_table('stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('landmark', sa.String(length=160), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stops'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('student', 'driver', 'admin', 'security', 'parent', name='user_role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('driver_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_no', sa.String(length=32), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_driver_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_driver_profiles')),
    sa.UniqueConstraint('license_no', name=op.f('uq_driver_profiles_license_no'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='notification_severity', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('route_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.SmallInteger(), nullable=False),
    sa.Column('offset_min', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_route_stops_route_id_routes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], name=op.f('fk_route_stops_stop_id_stops'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_stops')),
    sa.UniqueConstraint('route_id', 'sequence', deferrable=True, initially='DEFERRED', name='uq_route_stops_route_seq'),
    sa.UniqueConstraint('route_id', 'stop_id', name='uq_route_stops_route_stop')
    )
    op.create_index(op.f('ix_route_stops_route_id'), 'route_stops', ['route_id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('roll_no', sa.String(length=32), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('parent_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], name=op.f('fk_student_profiles_parent_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_student_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_student_profiles'))
    )
    op.create_index(op.f('ix_student_profiles_roll_no'), 'student_profiles', ['roll_no'], unique=True)
    op.create_table('trip_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('pickup', 'drop', name='trip_direction', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('days_of_week', sa.ARRAY(sa.SmallInteger()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], name=op.f('fk_trip_schedules_bus_id_buses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], name=op.f('fk_trip_schedules_driver_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_trip_schedules_route_id_routes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_schedules'))
    )
    op.create_index(op.f('ix_trip_schedules_route_id'), 'trip_schedules', ['route_id'], unique=False)
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('route_stop_id', sa.Integer(), nullable=True),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'ended', name='allocation_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.String(length=120), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_allocations_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_allocations_route_id_routes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_stop_id'], ['route_stops.id'], name=op.f('fk_allocations_route_stop_id_route_stops'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], name=op.f('fk_allocations_stop_id_stops'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_allocations_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allocations'))
    )
    op.create_index(op.f('ix_allocations_route_id'), 'allocations', ['route_id'], unique=False)
    op.create_index(op.f('ix_allocations_student_id'), 'allocations', ['student_id'], unique=False)
    op.create_index('uq_allocations_one_active_per_student', 'allocations', ['student_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('pickup', 'drop', name='trip_direction', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('scheduled_departure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'cancelled', name='trip_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_delay_min', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('cancel_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], name=op.f('fk_trips_bus_id_buses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], name=op.f('fk_trips_driver_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_trips_route_id_routes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schedule_id'], ['trip_schedules.id'], name=op.f('fk_trips_schedule_id_trip_schedules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips')),
    sa.UniqueConstraint('schedule_id', 'service_date', name='uq_trips_schedule_date')
    )
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trips_route_id'), 'trips', ['route_id'], unique=False)
    op.create_index(op.f('ix_trips_service_date'), 'trips', ['service_date'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_table('boardings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.Enum('qr', 'manual', name='boarding_method', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('allocation_match', sa.Boolean(), nullable=False),
    sa.Column('boarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_boardings_recorded_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], name=op.f('fk_boardings_stop_id_stops'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_boardings_student_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_boardings_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boardings')),
    sa.UniqueConstraint('trip_id', 'student_id', name='uq_boardings_trip_student')
    )
    op.create_index(op.f('ix_boardings_student_id'), 'boardings', ['student_id'], unique=False)
    op.create_index(op.f('ix_boardings_trip_id'), 'boardings', ['trip_id'], unique=False)
    op.create_table('bus_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed_kmph', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], name=op.f('fk_bus_positions_bus_id_buses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_bus_positions_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bus_positions'))
    )
    op.create_index(op.f('ix_bus_positions_recorded_at'), 'bus_positions', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_bus_positions_trip_id'), 'bus_positions', ['trip_id'], unique=False)
    op.create_table('delay_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('start', 'stop_arrival', 'overdue', 'not_started', 'manual', 'recovered', name='delay_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('delay_min', sa.SmallInteger(), nullable=False),
    sa.Column('at_sequence', sa.SmallInteger(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('reported_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], name=op.f('fk_delay_reports_reported_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_delay_reports_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delay_reports'))
    )
    op.create_index(op.f('ix_delay_reports_trip_id'), 'delay_reports', ['trip_id'], unique=False)
    op.create_table('trip_stop_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('route_stop_id', sa.Integer(), nullable=True),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('stop_name', sa.String(length=120), nullable=False),
    sa.Column('sequence', sa.SmallInteger(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delay_min', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['route_stop_id'], ['route_stops.id'], name=op.f('fk_trip_stop_events_route_stop_id_route_stops'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], name=op.f('fk_trip_stop_events_stop_id_stops'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_stop_events_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_stop_events')),
    sa.UniqueConstraint('trip_id', 'sequence', name='uq_trip_stop_events_seq')
    )
    op.create_index(op.f('ix_trip_stop_events_trip_id'), 'trip_stop_events', ['trip_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('present', 'absent', 'present_unallocated', name='attendance_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('boarding_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boarding_id'], ['boardings.id'], name=op.f('fk_attendance_records_boarding_id_boardings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_attendance_records_route_id_routes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_attendance_records_student_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_attendance_records_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records')),
    sa.UniqueConstraint('trip_id', 'student_id', name='uq_attendance_trip_student')
    )
    op.create_index(op.f('ix_attendance_records_service_date'), 'attendance_records', ['service_date'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_trip_id'), 'attendance_records', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_records_trip_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_service_date'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_trip_stop_events_trip_id'), table_name='trip_stop_events')
    op.drop_table('trip_stop_events')
    op.drop_index(op.f('ix_delay_reports_trip_id'), table_name='delay_reports')
    op.drop_table('delay_reports')
    op.drop_index(op.f('ix_bus_positions_trip_id'), table_name='bus_positions')
    op.drop_index(op.f('ix_bus_positions_recorded_at'), table_name='bus_positions')
    op.drop_table('bus_positions')
    op.drop_index(op.f('ix_boardings_trip_id'), table_name='boardings')
    op.drop_index(op.f('ix_boardings_student_id'), table_name='boardings')
    op.drop_table('boardings')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_service_date'), table_name='trips')
    op.drop_index(op.f('ix_trips_route_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index('uq_allocations_one_active_per_student', table_name='allocations', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_allocations_student_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_route_id'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_trip_schedules_route_id'), table_name='trip_schedules')
    op.drop_table('trip_schedules')
    op.drop_index(op.f('ix_student_profiles_roll_no'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_route_stops_route_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('driver_profiles')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('stops')
    op.drop_table('routes')
    op.drop_index(op.f('ix_domain_events_type'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_occurred_at'), table_name='domain_events')
    op.drop_index('ix_domain_events_aggregate', table_name='domain_events')
    op.drop_table('domain_events')
    op.drop_table('buses')
    # ### end Alembic commands ###
