"""master_data: bus assigned driver

Revision ID: 760c6592a8a4
Revises: bbfa08bf4a36
Create Date: 2026-09-24 12:23:48.367899
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '760c6592a8a4'
down_revision: Union[str, None] = 'bbfa08bf4a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buses', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_buses_driver_id'), 'buses', ['driver_id'])
    op.create_foreign_key(op.f('fk_buses_driver_id_users'), 'buses', 'users', ['driver_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_buses_driver_id_users'), 'buses', type_='foreignkey')
    op.drop_constraint(op.f('uq_buses_driver_id'), 'buses', type_='unique')
    op.drop_column('buses', 'driver_id')
    # ### end Alembic commands ###
